import type { Metadata } from "next";
import "./globals.css";
import AppProviders from "@/providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Minera San Cristobal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
